### ISSUE TITLE
Looking for printer.toolhead.homed_axis to include 'A,B,C'

### ISSUE THREAD

**Issue by adjustinthings** [naikymen/klipper-for-cnc#13]
I'm using moonnode in nodered to pull data in from moonraker for my robot automation project. I just switched to this klipper for cnc and it exactly what i need. 

It seems printer.toolhead.homed_axes doesn't display the A,B,C axis as homed. Is there another location that information is stored? 

OR is my moonraker just not able to get that info? (moonraker v0.8.0-209-g42357891)

I'm looking through cartesian_abc.py for clues currently.

**Comment by adjustinthings** [comment]
![image](https://github.com/naikymen/klipper-for-cnc/assets/37949962/771e06a3-752f-488c-b8c4-c861251a1b85)
oh i see

**Comment by naikymen** [comment]
Hey! Thanks for posting.

I completely forgot about the status stuff.

I just pushed a commit that should at least get the info out there: https://github.com/naikymen/klipper-for-cnc/commit/694f919b0cb886797ed22f52464249d89e818c44

Added also a `GET_STATUS_MSG` command which might help debug stuff:

![image](https://github.com/naikymen/klipper-for-cnc/assets/3259326/4fb156d7-cda2-43ae-86dd-a173b3321ca1)

**Comment by naikymen** [comment]
Please let me know if this is what you needed and how it goes :)

**Comment by naikymen** [comment]
Also added the extruder's status, in case it's home-able: https://github.com/naikymen/klipper-for-cnc/commit/87db854eadb226f64bfeaee4132a78dbe42e099a

Its messy but it seems to work.

**Comment by adjustinthings** [comment]
Hell yes. You rock, thank you. Works for me. I can see all the info in the printer.toolhead 👍. I'm using it to make a gantry automation system.

**Comment by naikymen** [comment]
Fantastic! Glad that it works now.

Could you share an image of your machine? Just curious :robot:

**Comment by adjustinthings** [comment]
I will get you this photo. I was trying to clean stuff up a bit. Its a
gantry system that attaches to the front of racking to pull things off the
shelf and move trays around.
