### ISSUE TITLE
Klipper reports: ERROR  Option 'kinematics_abc' is not valid in section 'printer'

### ISSUE THREAD

**Issue by xub** [naikymen/klipper-for-cnc#19]
[printer]
kinematics: cartesian_abc
# Units: mm/s and mm/s^2:
max_velocity: 5    # F120000
max_z_velocity: 5   # F30000
max_accel: 5
# Add ABC kinematics:
kinematics_abc: cartesian_abc
axis: XYZ

**Comment by naikymen** [comment]
Hola Sergio, gracias por probar mi rama.

Para ayudarte necesitaría el archivo log de klipper, que contenga el mensaje de error.

**Comment by naikymen** [comment]
Cierro el issue por inactividad. Cualquier cosa lo reabrimos!
