### ISSUE TITLE
 'ProbeEndstopWrapperG38' object has no attribute 'lower_probe' on G38.2

### ISSUE THREAD

**Issue by mapero** [naikymen/klipper-for-cnc#22]
**Describe the bug**
Hi @naikymen , after upgrading to the latest version, I get the error `'ProbeEndstopWrapperG38' object has no attribute 'lower_probe'` when trying to probe. I use `G38.2 Z0 F5`. This did work in the previous version.

What I found is:
https://github.com/naikymen/klipper-for-cnc/commit/acdf8bb1080ab829c6e8092dadf6d488aa416f77

Which made it private but not adapted in:
https://github.com/naikymen/klipper-for-cnc/blob/153751a57c176ab532e435e9b2e196687dcacdbb/klippy/extras/probe_G38.py#L56

**Comment by naikymen** [comment]
Hi! Sorry about it and thanks for fixing it :)
