### ISSUE TITLE
Project alive? And RS485 spindles support.

### ISSUE THREAD

**Issue by g992** [naikymen/klipper-for-cnc#9]
Hello! is the project still supported? and is it possible to connect rs 485 controlled spindle?

**Comment by naikymen** [comment]
Hi! Yes it is alive :)

I'm not sure that spindles are properly supported by (upstream) Klipper yet. Have you already tried to ask this question at the Klipper forum?

This is why I had not even considered spindles yet, but I just found that this has been discussed in the forum at least once, and a rudimentary extras module for spindle control has been written: https://klipper.discourse.group/t/klipper-cnc-spindle-rpm/8318

I imagine that getting precise spindle speed control would require a massive amount of work on the firmware side of Klipper, but I'm not savvy enough to give it a try.

Contributions would be very welcome!

**Comment by naikymen** [comment]
This might be of use to you as well: https://github.com/Klipper3d/klipper/pull/4128

Fast PWM updates are likely useful for spindle control.

**Comment by g992** [comment]
and i found this https://www.klipper3d.org/RPi_microcontroller.html
what about useing rpi2040 for pwm generation?

**Comment by naikymen** [comment]
Hello again! Sorry I missed your message entirely. Klipper has implemented proper PWM for tools (lasers, spindles, etc) upstream, and I have already merged it to this branch.

Does that feature fullfil your requirement?

**Comment by naikymen** [comment]
Closing due to inacivity.
